import gulpSvg from './gulp';
import linkedinSvg from './linkedin';
import githubSvg from './github';
import arrowUpSvg from './arrowUp';
import wordpressSvg from './wordpress';
import gruntSvg from './grunt';
import jquerySvg from './jquery';
import colorBarSvg from './colorBar';
import reactSvg from './react';
import calendarSvg from './calendar';
import codeSvg from './code';
import laptopSvg from './laptop';
import phpSvg from './php';
import vueSvg from './vue';
import javascriptSvg from './javascript';
import apiplatformSvg from './apiplatform';
import nextSvg from './next';
import webpackSvg from './webpack';
import laravelSvg from './laravel';

const svgIcons = {};

svgIcons.gulp = gulpSvg;
svgIcons.colorBar = colorBarSvg;
svgIcons.linkedin = linkedinSvg;
svgIcons.github = githubSvg;
svgIcons.arrowUp = arrowUpSvg;
svgIcons.wordpress = wordpressSvg;
svgIcons.grunt = gruntSvg;
svgIcons.jquery = jquerySvg;
svgIcons.react = reactSvg;
svgIcons.calendar = calendarSvg;
svgIcons.code = codeSvg;
svgIcons.laptop = laptopSvg;
svgIcons.php = phpSvg;
svgIcons.vue = vueSvg;
svgIcons.javascript = javascriptSvg;
svgIcons.apiplatform = apiplatformSvg;
svgIcons['next.js'] = nextSvg;
svgIcons.webpack = webpackSvg;
svgIcons.laravel = laravelSvg;

export default svgIcons;
